### ISSUE TITLE
Cannot install Bit via BVM

### ISSUE THREAD

**Issue by artem-tarasenko** [teambit/bvm#24]
Hey guys, I wanted to install Bit harmony, so I followed the Docs, installed BVM, and, well, tried to install Bit, here is the result:

```console
$ bvm install
Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined 
at GcpList.<anonymous> (C:\Users\tarasenko_ag\AppData\Roaming\npm\node_modules\@teambit\bvm\node_modules\@teambit\bvm.list\dist\gcp\gcp-list.js:27:42)     
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\tarasenko_ag\AppData\Roaming\npm\node_modules\@teambit\bvm\node_modules\@teambit\bvm.list\dist\gcp\gcp-list.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Cannot really say much about that since I barely started...
bvm - 0.0.30
node - 16.2.0
npm - 7.13.0

**Comment by ERRE216** [comment]
i had this problem recently too, try using a VPN.
