### ISSUE TITLE
Bit installation problem on windows 10.0.25227

### ISSUE THREAD

**Issue by dpetlyuk** [teambit/bvm#69]
When I try to install Bit, I get error:

```
bvm install
unsupported platform windows_nt
Error: unsupported platform windows_nt
    at validatePlatform (C:\Users\dpetl\AppData\Local\Yarn\Data\global\node_modules\@teambit\bvm.list\dist\list.js:47:15)
    at getGcpList (C:\Users\dpetl\AppData\Local\Yarn\Data\global\node_modules\@teambit\bvm.list\dist\list.js:35:5)
    at C:\Users\dpetl\AppData\Local\Yarn\Data\global\node_modules\@teambit\bvm.list\dist\list.js:56:25
    at Generator.next (<anonymous>)
    at C:\Users\dpetl\AppData\Local\Yarn\Data\global\node_modules\@teambit\bvm.list\dist\list.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\dpetl\AppData\Local\Yarn\Data\global\node_modules\@teambit\bvm.list\dist\list.js:4:12)
    at listRemote (C:\Users\dpetl\AppData\Local\Yarn\Data\global\node_modules\@teambit\bvm.list\dist\list.js:55:12)
    at C:\Users\dpetl\AppData\Local\Yarn\Data\global\node_modules\@teambit\bvm.install\dist\install.js:49:75
    at Generator.next (<anonymous>)
```

I guess this is because of OS detects as windows_nt, not win.

**Comment by GiladShoham** [comment]
I believe it should work now, please check with latest bvm version and let me know. thanks

**Comment by dpetlyuk** [comment]
Yes, thank you! All works.
