### ISSUE TITLE
Facing an Unexpected Token issue when building

### ISSUE THREAD

**Issue by alanoudssr** [teambit/bvm#79]
```
/usr/local/lib/node_modules/[@teambit](https://t.me/teambit)/bvm/node_modules/[@pnpm](https://t.me/pnpm)/fetch/lib/fetch.js:38
    const retryOpts = opts.retry ?? {};
                                  ^

SyntaxError: Unexpected token ‘?’
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
```

I've been facing this issue in Jenkins build when using bvm during the `bvm verions` `bvm install` part

**Comment by zkochan** [comment]
Update your Node.js version to v14 or newer.

**Comment by deitux123** [comment]
What about those who use node 12?

**Comment by GiladShoham** [comment]
stale.
closing.
bvm only supported from node 20 or higher at the moment of this comment.
