### ISSUE TITLE
'bvm remove --all' throws exception and deadlocks

### ISSUE THREAD

**Issue by mathias-falkenberg** [teambit/bvm#83]
OS: Windows 10 Enterprise (10.0.19045)
bvm v0.3.1
node v18.15.0
npm v9.5.0

I have multiple versions of bit installed:
```
➜ bvm list
0.0.888
0.1.11
0.1.4
0.1.7
```

The help text for `bvm` provides a broken example for removal (`bvm remove all --keep-latest-versions 3`). Running `bvm remove -h`, however, provides the proper `--all` switch syntax.

Running `bit remove --all` yields the following:
```
➜ bvm remove --all
⠹ removing versions from the file systemCannot read properties of undefined (reading 'removeVersions')
TypeError: Cannot read properties of undefined (reading 'removeVersions')
    at C:\ProgramData\nvm\v18.15.0\node_modules\@teambit\bvm\node_modules\@teambit\bvm.remove\dist\remove.js:65:21
    at Generator.next (<anonymous>)
    at fulfilled (C:\ProgramData\nvm\v18.15.0\node_modules\@teambit\bvm\node_modules\@teambit\bvm.remove\dist\remove.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
⠏ removing versions from the file system
```

After this, the command seems to be stuck in an infinite loop.

**Comment by GiladShoham** [comment]
This was already fixed in 92f750a (#85), released in v0.4.0:
- The broken help example (`bvm remove all --keep-latest-versions 3`) was corrected to `bvm remove --all --keep-latest-versions 3`.
- The crash (`Cannot read properties of undefined (reading 'removeVersions')`) was caused by `return this.removeVersions(...)` inside the standalone exported `removeAll()` function, where `this` was `undefined`. Fixed to call `removeVersions(...)` directly.

Anyone on v0.4.0+ should no longer hit this. Closing.

While verifying this, I found an unrelated latent bug in the same function, filed separately as #127.
