### ISSUE TITLE
trying to install nightly version without configure nightly throws exception

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bvm#91]
reproduce 
```
bvm config set RELEASE_TYPE stable
bvm install <nightly version number>
```

error
```
Cannot read properties of undefined (reading 'filter')
TypeError: Cannot read properties of undefined (reading 'filter')
    at GcpList.<anonymous> (/Users/gilad/.nvm/versions/node/v16.20.0/lib/node_modules/@teambit/bvm/node_modules/@teambit/bvm.list/dist/gcp/gcp-list.js:60:51)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/gilad/.nvm/versions/node/v16.20.0/lib/node_modules/@teambit/bvm/node_modules/@teambit/bvm.list/dist/gcp/gcp-list.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by GiladShoham** [comment]
This no longer reproduces. Tested against the current published `bvm@3.1.3` with the exact repro:

```
bvm config set RELEASE_TYPE stable
bvm install <nightly version>
```

- With the default install method (`package-manager`), it installs successfully — that path fetches the version's lockfile directly by version number and never consults the release-type filter, so the crash's root cause doesn't come into play at all.
- With the tar fallback method (`--method tar`), it no longer crashes either — `gcp-list.ts` now returns a clean "version X not found on remote, use bvm list --remote to see available versions" message instead of calling `.filter` on an undefined array.

There's a minor residual UX gap: on the tar path specifically, installing a specific nightly version while `RELEASE_TYPE=stable` fails with that "not found" message rather than installing it (it could in principle still find it, since the version does exist). That's a much milder issue than the original unhandled `TypeError` crash and worth tracking separately if it matters.

Closing since the reported crash is fixed.
